import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faArrowRightFromBracket,
  faArrowTrendUp,
  faBagShopping,
  faBasketShopping,
  faBolt,
  faBrush,
  faBuildingColumns,
  faBus,
  faChartColumn,
  faChartPie,
  faCircleCheck,
  faCircleExclamation,
  faPalette,
  faDatabase,
  faEllipsis,
  faGear,
  faGift,
  faGraduationCap,
  faHeartPulse,
  faHouse,
  faMoon,
  faPaw,
  faPenToSquare,
  faPiggyBank,
  faPlus,
  faReceipt,
  faRoute,
  faLayerGroup,
  faCode,
  faBook,
  faGlobe,
  faIdCard,
  faShirt,
  faSun,
  faTag,
  faTrashCan,
  faUtensils,
  faUser,
  faUsers,
  faWallet,
  faWandMagicSparkles,
} from '@fortawesome/free-solid-svg-icons'
import type { App } from 'vue'

library.add(
  faArrowRightFromBracket,
  faArrowTrendUp,
  faBagShopping,
  faBasketShopping,
  faBolt,
  faBrush,
  faBuildingColumns,
  faBus,
  faChartColumn,
  faChartPie,
  faCircleCheck,
  faCircleExclamation,
  faDatabase,
  faEllipsis,
  faGear,
  faGift,
  faGraduationCap,
  faHeartPulse,
  faHouse,
  faMoon,
  faPalette,
  faPaw,
  faPenToSquare,
  faPiggyBank,
  faPlus,
  faReceipt,
  faRoute,
  faLayerGroup,
  faCode,
  faBook,
  faGlobe,
  faIdCard,
  faShirt,
  faSun,
  faTag,
  faTrashCan,
  faUtensils,
  faUser,
  faUsers,
  faWallet,
  faWandMagicSparkles
)

export function registerFontAwesome(app: App) {
  app.component('FontAwesomeIcon', FontAwesomeIcon)
}
